##### Page d'accueil de l'application #####
wcpc2k18_home:
    path: /
    defaults: { _controller: WCPC2K18Bundle:Home:index }


##### Liste des rencontres #####
wcpc2k18_games:
    path: /rencontres
    defaults: { _controller: WCPC2K18Bundle:Game:list }
    
    
##### Listes des joueurs participant #####
wcpc2k18_users:
    path: /participants
    defaults: { _controller: WCPC2K18Bundle:User:list }
    
##### Liste des services engagés #####
wcpc2k18_crews:
    path: /services
    defaults: { _controller: WCPC2K18Bundle:Crew:list }


#### Classements #####
wcpc2k18_leaderboard:
    path: /classement
    defaults: { _controller: WCPC2K18Bundle:Leaderboard:index } 

#### Règles du jeu ####
wcpc2k18_rules:
    path: /regles
    defaults: { _controller: WCPC2K18Bundle:Rule:index }

### Formulaire de saisie d'un pronostic ####
wcpc2k18_form_prediction:
    path: /rencontre/{gameId}/pronostic
    defaults: { _controller: WCPC2K18Bundle:Form:prediction }
    
### Formulaire de saisie du résultat d'une rencontre ###
wcpc2k18_form_game:
    path: /rencontre/{gameId}/resultat
    defaults: { _controller: WCPC2K18Bundle:Form:game }
    
### Accès au détail d'une rencontre
wcpc2k18_game:
    path: /rencontre/{gameId}/detail
    defaults: { _controller: WCPC2K18Bundle:Game:show }
    
    