services:
#    wcpc2_k18.example:
#        class: WCPC2K18Bundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    wcpc2k18.twig_extension:
        class: WCPC2K18Bundle\Twig\WCPC2K18Extension
        public: false
        tags:
            - { name : twig.extension }
